"""Pure-Python port of the site-symmetry engine (src/sitesym.F90, used when
``lsitesymmetry=True``): imposes space-group symmetry during
disentanglement and Wannierisation, following R. Sakuma, "Symmetry-adapted
Wannier functions in the maximal localization procedure", PRB 87, 235109
(2013).

Only ``irreducible`` k-points (``nkptirr`` of them, out of the full
``num_kpts``-point mesh) are ever independently computed; the rest of the
Brillouin zone is reconstructed from them via the symmetry operations'
representation matrices on the Bloch (``d_matrix_band``) and Wannier-gauge
(``d_matrix_wann``) bases -- both supplied externally in a ``.dmn`` file
(see ``io_helpers.read_dmn``; not generated by this package or by Wannier90
itself, produced by an external symmetry-detection tool, e.g. a
``pw2wannier90`` interface with spglib support).

All array indices here are 0-indexed Python/NumPy convention; the Fortran
source (extensively cross-referenced in comments) is 1-indexed throughout,
and so are the *contents* of ``ir2ik``/``ik2ir``/``kptsym`` as parsed by
``read_dmn`` (converted to 0-indexed only where used to index an array).

Not ported: the frozen-window disentanglement case (Fortran itself doesn't
support it in symmetry-adapted mode either -- "frozen window not
implemented yet in symmetry-adapted mode").
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class SymmetryData:
    nsymmetry: int
    nkptirr: int
    num_kpts: int
    ik2ir: np.ndarray  # (num_kpts,) 0-indexed into 0..nkptirr-1
    ir2ik: np.ndarray  # (nkptirr,) 0-indexed into 0..num_kpts-1
    kptsym: np.ndarray  # (nsymmetry, nkptirr) 0-indexed into 0..num_kpts-1
    d_matrix_wann: np.ndarray  # (num_wann, num_wann, nsymmetry, nkptirr)
    d_matrix_band: np.ndarray  # (num_bands_or_window, num_bands_or_window, nsymmetry, nkptirr)


def from_dmn(dmn, num_wann: int) -> SymmetryData:
    """Build a :class:`SymmetryData` from an ``io_helpers.DmnData`` (still
    1-indexed there) and validate it against ``num_wann``."""
    if dmn.d_matrix_wann.shape[0] != num_wann:
        raise ValueError(
            f".dmn file's D-matrices are sized for num_wann={dmn.d_matrix_wann.shape[0]}, "
            f"but this calculation has num_wann={num_wann}"
        )
    return SymmetryData(
        nsymmetry=dmn.nsymmetry, nkptirr=dmn.nkptirr, num_kpts=dmn.num_kpts,
        ik2ir=dmn.ik2ir - 1, ir2ik=dmn.ir2ik - 1, kptsym=dmn.kptsym - 1,
        d_matrix_wann=dmn.d_matrix_wann.copy(), d_matrix_band=dmn.d_matrix_band.copy(),
    )


def slim_d_matrix_band(d_matrix_band: np.ndarray, lwindow: np.ndarray, ir2ik: np.ndarray) -> np.ndarray:
    """Reindex ``d_matrix_band`` from absolute band index to window-relative
    index, mirroring ``disentangle.py``'s ``slim_m`` -- but only defined at
    each star's representative k-point (``ir2ik``); every k-point in a star
    is assumed to share the same window (required for symmetry to make
    sense, and enforced by frozen windows being unsupported here)."""
    num_bands = d_matrix_band.shape[0]
    out = np.zeros_like(d_matrix_band)
    for ir in range(len(ir2ik)):
        ik = ir2ik[ir]
        nindx = np.nonzero(lwindow[:, ik])[0]
        nb = len(nindx)
        out[:nb, :nb, :, ir] = d_matrix_band[np.ix_(nindx, nindx)][:, :, :, ir]
    return out


def _orthogonalize(u: np.ndarray, n: int) -> np.ndarray:
    """Lowdin-orthogonalize ``u[:n, :]`` via SVD (``orthogonalize_u``) --
    same U = Z @ Vh pattern as ``overlap.py``/``disentangle.py``."""
    m = u.shape[1]
    if n < m:
        raise ValueError("orthogonalize_u: n < m")
    Z, _, Vh = np.linalg.svd(u[:n, :], full_matrices=True)
    out = u.copy()
    out[:n, :] = Z[:, :m] @ Vh
    return out


def symmetrize_ukirr(ir: int, umat: np.ndarray, sym: SymmetryData, n: int,
                      symmetrize_eps: float = 1.0e-3, niter: int = 100) -> np.ndarray:
    """u~(k) = 1/N_R' sum_{R': R'k=k} d^dagger(R',k) u(k) D(R',k), then
    re-orthonormalize -- the fixed-point iteration ``symmetrize_ukirr``
    averages a trial U(k) over k's own little group until it's invariant
    under it (to within ``symmetrize_eps``)."""
    ik = sym.ir2ik[ir]
    little_group = np.nonzero(sym.kptsym[:, ir] == ik)[0]
    ngk = len(little_group)
    num_wann = umat.shape[1]

    if ngk == 1:
        return _orthogonalize(umat, n)

    u = umat.copy()
    for iteration in range(niter):
        usum = np.zeros_like(u)
        cmat2 = ngk * np.eye(num_wann, dtype=complex)
        for isym in little_group:
            cmat_sub = u[:n, :] @ sym.d_matrix_wann[:, :, isym, ir]
            cmat = sym.d_matrix_band[:n, :n, isym, ir].conj().T @ cmat_sub
            usum[:n, :] += cmat
            cmat2 -= u[:n, :].conj().T @ cmat
        diff = float(np.sum(np.abs(cmat2)))
        if diff < symmetrize_eps:
            break
        if iteration == niter - 1:
            raise ValueError(
                f"symmetrize_ukirr: not converged (diff={diff}, symmetrize_eps={symmetrize_eps}) "
                "-- either eps is too small or the specified irreps are not compatible with the bands"
            )
        usum[:n, :] /= ngk
        u = _orthogonalize(usum, n)
    return u


def symmetrize_u_matrix(umat: np.ndarray, sym: SymmetryData, lwindow: np.ndarray | None = None,
                         symmetrize_eps: float = 1.0e-3) -> np.ndarray:
    """U(Rk) = d(R,k) U(k) D^dagger(R,k): symmetrize U at each star's
    representative k-point, then propagate to the rest of the star.

    ``lwindow`` present => disentanglement phase (``ndim = num_bands``,
    ``d = d_matrix_band``, already window-sliced via
    :func:`slim_d_matrix_band`); absent => Wannierisation phase
    (``ndim = num_wann``, ``d = d_matrix_band`` is really
    ``d_matrix_wann`` too by then, see ``disentangle.py``'s
    ``replace_d_matrix_band`` equivalent in ``_engine/__init__.py``)."""
    num_kpts = umat.shape[2]
    num_wann = umat.shape[1]
    out = umat.copy()
    done = np.zeros(num_kpts, dtype=bool)

    for ir in range(sym.nkptirr):
        ik = sym.ir2ik[ir]
        done[ik] = True
        n = int(np.count_nonzero(lwindow[:, ik])) if lwindow is not None else out.shape[0]
        out[:, :, ik] = symmetrize_ukirr(ir, out[:, :, ik], sym, n, symmetrize_eps)
        for isym in range(1, sym.nsymmetry):
            irk = sym.kptsym[isym, ir]
            if done[irk]:
                continue
            done[irk] = True
            cmat = sym.d_matrix_band[:n, :n, isym, ir] @ out[:n, :, ik]
            out[:n, :, irk] = cmat @ sym.d_matrix_wann[:, :, isym, ir].conj().T

    if not np.all(done):
        raise ValueError("symmetrize_u_matrix: not every k-point was reached from an irreducible one")
    return out


def symmetrize_gradient(imode: int, grad: np.ndarray, sym: SymmetryData) -> np.ndarray:
    """imode=1 (``wann_domega``'s raw gradient): fold every k-point's
    contribution into its star's representative, then zero out the rest.
    imode=2 (the CG search direction): skip that (it's already
    representative-only), just re-symmetrize under each representative's
    own little group. Both modes always end with the little-group
    self-consistency step."""
    num_kpts = grad.shape[2]
    out = grad.copy()

    if imode == 1:
        found = np.zeros(num_kpts, dtype=bool)
        for ir in range(sym.nkptirr):
            ik = sym.ir2ik[ir]
            total = out[:, :, ik].copy()
            found[ik] = True
            for isym in range(1, sym.nsymmetry):
                irk = sym.kptsym[isym, ir]
                if found[irk]:
                    continue
                found[irk] = True
                cmat2 = sym.d_matrix_wann[:, :, isym, ir].conj().T @ out[:, :, irk]
                total = total + cmat2 @ sym.d_matrix_wann[:, :, isym, ir]
            out[:, :, ik] = total
        for ik in range(num_kpts):
            if sym.ir2ik[sym.ik2ir[ik]] != ik:
                out[:, :, ik] = 0.0

    for ir in range(sym.nkptirr):
        ik = sym.ir2ik[ir]
        little_group = np.nonzero(sym.kptsym[:, ir] == ik)[0]
        ngk = len(little_group)
        if ngk == 1:
            continue
        total = out[:, :, ik].copy()
        for isym in little_group:
            if isym == 0:
                continue
            cmat2 = out[:, :, ik] @ sym.d_matrix_wann[:, :, isym, ir]
            total = total + sym.d_matrix_wann[:, :, isym, ir].conj().T @ cmat2
        out[:, :, ik] = total / ngk

    return out


def symmetrize_rotation(urot: np.ndarray, sym: SymmetryData) -> np.ndarray:
    """urot(Rk) = D(R,k) urot(k) D^dagger(R,k): propagate a
    num_wann-gauge rotation (e.g. the CG step's matrix exponential) from
    each star's representative to the rest of the star."""
    num_kpts = urot.shape[2]
    out = urot.copy()
    done = np.zeros(num_kpts, dtype=bool)

    for ir in range(sym.nkptirr):
        ik = sym.ir2ik[ir]
        done[ik] = True
        for isym in range(1, sym.nsymmetry):
            irk = sym.kptsym[isym, ir]
            if irk == ik or done[irk]:
                continue
            done[irk] = True
            cmat2 = out[:, :, ik] @ sym.d_matrix_wann[:, :, isym, ir].conj().T
            out[:, :, irk] = sym.d_matrix_wann[:, :, isym, ir] @ cmat2

    if not np.all(done):
        raise ValueError("symmetrize_rotation: not every k-point was reached from an irreducible one")
    return out


def symmetrize_zmatrix(czmat: np.ndarray, sym: SymmetryData, lwindow: np.ndarray) -> np.ndarray:
    """Z(k) <- 1/N_R' [Z(k) + sum_{R' in own little group, R'!=E} d^dagger Z(k) d
    + sum_{R: Rk'=k, k'!=k} d^dagger(R) Z(k') d(R)] -- fold in both the
    star's other members and k's own little-group self-consistency."""
    num_kpts = czmat.shape[2]
    out = czmat.copy()
    found = np.zeros(num_kpts, dtype=bool)

    for ir in range(sym.nkptirr):
        ik = sym.ir2ik[ir]
        nd = int(np.count_nonzero(lwindow[:, ik]))
        found[ik] = True
        for isym in range(1, sym.nsymmetry):
            irk = sym.kptsym[isym, ir]
            if found[irk]:
                continue
            found[irk] = True
            cmat1 = out[:nd, :nd, irk] @ sym.d_matrix_band[:nd, :nd, isym, ir]
            out[:nd, :nd, ik] += sym.d_matrix_band[:nd, :nd, isym, ir].conj().T @ cmat1

        snapshot = out[:nd, :nd, ik].copy()
        for isym in range(1, sym.nsymmetry):
            if sym.kptsym[isym, ir] != ik:
                continue
            cmat1 = snapshot @ sym.d_matrix_band[:nd, :nd, isym, ir]
            out[:nd, :nd, ik] += sym.d_matrix_band[:nd, :nd, isym, ir].conj().T @ cmat1

        out[:nd, :nd, ik] /= int(np.count_nonzero(sym.kptsym[:, ir] == ik))

    return out


def _solve_2x2_generalized_eigh(H: np.ndarray, S: np.ndarray):
    """Eigenvalues/vectors (ascending) of the 2x2 generalized Hermitian
    problem H v = w S v, S positive-definite -- via Cholesky reduction to
    an ordinary Hermitian eigenproblem, using only ``numpy.linalg`` (no
    scipy dependency)."""
    L = np.linalg.cholesky(S)  # S = L L^H
    L_inv = np.linalg.inv(L)
    H_prime = L_inv @ H @ L_inv.conj().T
    w, y = np.linalg.eigh(H_prime)
    v = L_inv.conj().T @ y
    return w, v


def dis_extract_symmetry(ik: int, n: int, zmat: np.ndarray, umat: np.ndarray, sym: SymmetryData,
                          symmetrize_eps: float = 1.0e-3, niter: int = 50):
    """Replaces direct Z-matrix diagonalization (the non-symmetric
    ``dis_extract``'s ``internal_zmatrix`` + eigensolve) with a symmetry-
    respecting steepest-descent extraction: for each Wannier function,
    build the 2D subspace spanned by {current column, steepest-descent
    step} and take the linear combination that maximizes the Rayleigh
    quotient against Z (a 2x2 generalized eigenproblem), then
    re-symmetrize the whole matrix each iteration.

    Returns (umat, lambda) -- lambda = U^dagger Z U (Lagrange multipliers,
    diagnostic only, matching the Fortran signature)."""
    num_bands, num_wann = umat.shape
    u = umat.copy()
    lam = np.zeros((num_wann, num_wann), dtype=complex)

    for _ in range(niter):
        ZU = zmat[:, :n] @ u[:n, :]  # (n, num_wann), zero beyond row n like the Fortran leading-dim convention
        ZU_full = np.zeros((num_bands, num_wann), dtype=complex)
        ZU_full[:n, :] = ZU
        lam = u[:n, :].conj().T @ ZU
        deltaU = np.zeros((num_bands, num_wann), dtype=complex)
        deltaU[:n, :] = ZU - u[:n, :] @ lam
        if np.sum(np.abs(deltaU[:n, :])) < 1.0e-10:
            return u, lam

        u_new = u.copy()
        for i in range(num_wann):
            ui, zui, dui = u[:n, i], ZU_full[:n, i], deltaU[:n, i]
            sp3 = float(np.vdot(dui, dui).real)
            if abs(sp3) < 1.0e-10:
                continue
            H = np.array([
                [np.vdot(ui, zui).real, np.vdot(zui, dui)],
                [np.conj(np.vdot(zui, dui)), float(np.vdot(dui, zmat[:n, :n] @ dui).real)],
            ], dtype=complex)
            S = np.array([
                [np.vdot(ui, ui).real, np.vdot(ui, dui)],
                [np.conj(np.vdot(ui, dui)), sp3],
            ], dtype=complex)
            _, V = _solve_2x2_generalized_eigh(H, S)
            u_new[:n, i] = V[0, 1] * ui + V[1, 1] * dui  # largest eigenvalue (ascending order -> last column)
        u = symmetrize_ukirr(sym.ik2ir[ik], u_new, sym, n, symmetrize_eps)

    return u, lam
