"""The quantics tensor-train BSE solver.

The chain being tested is: PairOracle evaluates the pair basis one
k-point at a time; LazyKernel gives any matrix element of X - D from it;
qutecipy cross-interpolates that into an MPO; pyitensor's DMRG
diagonalizes it. Each link is pinned separately against something exact,
because a failure anywhere in it looks the same from the outside -- a
plausible number that is slightly wrong.

There is no comparable open implementation to benchmark against (Xatu,
whose formalism bsetk/ follows, uses a dense solver; TensorBinding, the
closest tensor-network tight-binding code, has no exciton module), so the
substitutes are internal: the dense solver where it still runs, and the
matrix-free solver -- exact, and independent of every tensor-train choice
-- past that.
"""
import numpy as np
import pytest

pytest.importorskip("dmrgpy", reason="the quantics BSE solver uses "
                    "dmrgpy.pyitensor's DMRG")

from testutils import gapped_ionic_chain, gapped_honeycomb
from pyqula import geometry
from pyqula.bsetk.interaction import density_interaction, bare_interaction
from pyqula.bsetk.pairbasis import PairBasis
from pyqula.bsetk.oracle import PairOracle
from pyqula.bsetk.factorize import KernelFactorization
from pyqula.bsetk import qtt


def spinless_chain(stagger=0.9):
    """A gapped, spinless, NON-degenerate two-band chain. Spinless keeps
    the tensor-train ranks small enough for a fast test; the degenerate
    spinful case is covered by test_bse_gauge.py's rank measurements and
    by test_qtt_spinful_matches_dense below."""
    g = geometry.chain().supercell(2)
    h = g.get_hamiltonian(has_spin=False)
    h.add_onsite(lambda r: stagger * (-1) ** int(round(r[0] - 0.5)))
    return h.get_multicell().get_dense()


def mpo_to_dense(mpo):
    """Contract an MPO back to a matrix. Tests only, obviously."""
    from dmrgpy.pyitensor.tensor import commonIndex
    res = np.ones((1, 1, 1), dtype=np.complex128)  # (row, col, bond)
    for i in range(1, mpo.length() + 1):
        T = mpo.A(i)
        s = [x for x in T.inds if x.hastags("Site")]
        s0 = [x for x in s if x.plev == 0][0]   # unprimed = ket = column
        s1 = [x for x in s if x.plev == 1][0]   # primed   = bra = row
        l = commonIndex(mpo.A(i), mpo.A(i - 1)) if i > 1 else None
        r = commonIndex(mpo.A(i), mpo.A(i + 1)) if i < mpo.length() else None
        a = T.transpose_to([x for x in (l, s0, s1, r) if x is not None])
        if l is None: a = a[None]
        if r is None: a = a[..., None]
        res = np.einsum("MNl,lnmr->MmNnr", res, a)
        res = res.reshape(res.shape[0] * res.shape[1],
                          res.shape[2] * res.shape[3], res.shape[4])
    return res[:, :, 0]


# ---------------------------------------------------------------- oracle

@pytest.mark.parametrize("gauge", [None, "phase", "projection"])
def test_oracle_reproduces_the_pair_basis(gauge):
    """PairOracle must produce exactly what PairBasis does, k-point by
    k-point -- including the mesh ordering, which it regenerates from the
    index instead of calling geometry.get_kmesh"""
    h = spinless_chain()
    nk = 8
    pb = PairBasis(h, Q=[0.25, 0., 0.], nk=nk, gauge=gauge)
    po = PairOracle(h, Q=[0.25, 0., 0.], nk=nk, gauge=gauge, coarse_nk=nk)
    assert po.npair == pb.npair
    assert po.vbands == pb.vbands and po.cbands == pb.cbands
    ks = np.array([po.kpoint(i) for i in range(nk)])
    assert np.max(np.abs(ks - pb.kpoints)) < 1e-14
    dE, el, ho = po.pair_arrays(np.arange(po.npair))
    assert np.max(np.abs(dE - pb.dE)) < 1e-12
    assert np.max(np.abs(el - pb.el)) < 1e-12
    assert np.max(np.abs(ho - pb.ho)) < 1e-12


def test_oracle_mesh_order_matches_get_kmesh_in_2d():
    """The k index is generated by bit arithmetic, so its correspondence
    to geometry.get_kmesh's own ordering is an assumption that has to be
    checked rather than believed -- in 2D above all, where a transposed
    convention would still give a plausible spectrum"""
    h = gapped_honeycomb(spinful=False)
    nk = 8
    po = PairOracle(h, nk=nk, coarse_nk=nk)
    ref = np.array(h.geometry.get_kmesh(nk=nk))
    got = np.array([po.kpoint(i) for i in range(nk * nk)])
    assert np.max(np.abs(got - ref)) < 1e-14


# ---------------------------------------------------------- kernel + MPO

@pytest.mark.parametrize("kernel", ["full", "direct", "exchange"])
def test_lazy_kernel_matches_the_dense_kernel(kernel):
    h = spinless_chain()
    W = bare_interaction(h, V=density_interaction(h, V1=0.8, V2=0.3))
    nk = 8
    pb = PairBasis(h, Q=[0.25, 0., 0.], nk=nk, gauge="projection")
    po = PairOracle(h, Q=[0.25, 0., 0.], nk=nk, gauge="projection",
                    coarse_nk=nk)
    f = KernelFactorization(pb, W, Wx=W, kernel=kernel, block="A")
    ref = f.to_dense() - np.diag(f.diag)   # the interaction part alone
    lk = qtt.LazyKernel(po, W, Wx=W, kernel=kernel)
    got = np.array([[lk.element(m, n) for n in range(po.npair)]
                    for m in range(po.npair)])
    assert np.max(np.abs(got - ref)) < 1e-13


@pytest.mark.parametrize("nk", [8, 16])
def test_mpo_reproduces_the_dense_block(nk):
    """The MPO is built by cross-interpolating matrix elements, never by
    decomposing a matrix -- so that it reproduces the matrix is a real
    check, not a tautology"""
    h = spinless_chain()
    W = bare_interaction(h, V=density_interaction(h, V1=0.8))
    pb = PairBasis(h, nk=nk, gauge="projection")
    po = PairOracle(h, nk=nk, gauge="projection", coarse_nk=nk)
    ref = KernelFactorization(pb, W, Wx=W, kernel="full",
                              block="A").to_dense()
    lk = qtt.LazyKernel(po, W, Wx=W, kernel="full")
    grid = qtt.quantics_grid(po)
    mpo = qtt.build_mpo(lk, grid, tolerance=1e-12)
    assert np.max(np.abs(mpo_to_dense(mpo) - ref)) < 1e-10


def test_grid_index_is_the_pair_index():
    """quantics grid index <-> flat pair index, in 2D with band sites.
    Getting this wrong permutes the whole problem silently."""
    h = gapped_honeycomb(spinful=True)   # 2 valence, 2 conduction bands
    po = PairOracle(h, nk=4, coarse_nk=4)
    grid = qtt.quantics_grid(po)
    seen = set()
    for m in range(po.npair):
        ik = m // po.nband
        ib = m % po.nband
        iv, ic = divmod(ib, len(po.cbands))
        ix, iy = divmod(ik, po.nk)
        gi = (ix, iy) + _digits(iv, grid.pyqula_vsizes) \
                      + _digits(ic, grid.pyqula_csizes)
        assert qtt.grid_to_pair(grid, gi) == m, (m, gi)
        seen.add(qtt.grid_to_pair(grid, gi))
    assert len(seen) == po.npair          # a bijection, not just injective


def _digits(i, sizes):
    """Mixed-radix digits of i for the given per-variable sizes"""
    out = []
    for s in reversed(sizes):
        i, r = divmod(i, s)
        out.append(r)
    return tuple(reversed(out))


@pytest.mark.parametrize("nv,nc", [(1, 1), (2, 2)])
def test_band_index_is_split_across_sites(nv, nc):
    """A band window must not sit on one site of dimension nv*nc: that
    site becomes (nv*nc)^2 wide in the MPO, and cross interpolation has to
    sample all of it per pivot. Factorizing keeps every site at the
    largest prime factor instead."""
    h = gapped_honeycomb(spinful=True)
    po = PairOracle(h, nk=4, coarse_nk=4, nv=nv, nc=nc)
    grid = qtt.quantics_grid(po)
    dims = list(grid.localdimensions())
    assert int(np.prod(dims)) == po.npair       # still the same problem
    band_dims = dims[2 * 2:]                    # after the 2x2 k-bits
    assert int(np.prod(band_dims)) == nv * nc
    if band_dims:
        assert max(band_dims) <= max(max(_pf(nv)), max(_pf(nc)))


def test_supercell_band_window_is_not_one_wide_site():
    """The case that motivated the factorization: a 3x3 supercell of the
    honeycomb has 9 valence and 9 conduction bands. On one site that is a
    band index of 81, and 6561 once the MPO fuses row and column. Split
    and factorized it is four sites of 3, i.e. 9 in the MPO."""
    from pyqula import geometry
    g = geometry.honeycomb_lattice().supercell(3)
    h = g.get_hamiltonian(has_spin=False)
    h.add_sublattice_imbalance(0.8)
    h = h.get_multicell().get_dense()
    po = PairOracle(h, nk=4, coarse_nk=4)
    assert len(po.vbands) == 9 and len(po.cbands) == 9
    grid = qtt.quantics_grid(po)
    band_dims = list(grid.localdimensions())[2 * 2:]
    assert band_dims == [3, 3, 3, 3], band_dims
    assert max(band_dims) ** 2 == 9              # widest MPO site, not 6561


def _pf(n):
    return [b for b, r in qtt.prime_factors(n)] or [1]


def test_prime_factorization_of_the_band_window():
    for n, want in [(1, 1), (2, 2), (4, 4), (6, 6), (7, 7), (8, 8), (9, 9),
                    (81, 81)]:
        f = qtt.prime_factors(n)
        assert int(np.prod([b ** r for b, r in f])) == want
    assert qtt.prime_factors(1) == []
    assert qtt.prime_factors(9) == [(3, 2)]     # two sites of 3, not one of 9
    assert qtt.prime_factors(8) == [(2, 3)]


# ------------------------------------------------------------ end to end

def test_qtt_matches_dense_chain():
    h = spinless_chain()
    V = density_interaction(h, V1=0.8)
    for nk in (8, 16, 32):
        ref = h.get_bse(V=V, nk=nk, tda=True).get_energies(n=1)[0].real
        got = h.get_bse(V=V, nk=nk, tda=True, solver="qtt", neig=1,
                        tolerance=1e-10, coarse_nk=8).get_energies()[0].real
        assert abs(got - ref) < 1e-8, (nk, got, ref)


@pytest.mark.parametrize("nk", [1024, 4096])
def test_qtt_matches_iterative_past_the_dense_wall(nk):
    """The comparison that stays available as the mesh grows.

    bsetk/iterative.py applies the exact kernel and is independent of
    every tensor-train choice made here -- the gauge, the cross
    interpolation, the MPO, DMRG -- so agreement between the two is a real
    check rather than two versions of the same code agreeing. At these
    mesh sizes the dense solver is already out of reach."""
    h = spinless_chain()
    V = density_interaction(h, V1=0.8)
    ref = h.get_bse(V=V, nk=nk, tda=True, solver="iterative",
                    neig=1).get_energies()[0].real
    b = h.get_bse(V=V, nk=nk, tda=True, solver="qtt", neig=1,
                  tolerance=1e-10, coarse_nk=8)
    assert abs(b.get_energies()[0].real - ref) < 1e-7


def test_qtt_diagonalizes_far_fewer_k_points_than_the_mesh():
    """The claim the whole solver exists for.

    Cross interpolation visits a number of k-points set by the
    tensor-train rank, not by the mesh, so refining the mesh 16-fold must
    not cost 16 times the diagonalizations. Measured on this model, number
    of k-points actually diagonalized against the mesh size:

      nk      256  1024  4096  16384  65536  262144
      ndiag   256  1021  2767   5051   6717    7455

    i.e. growing like log(nk) while the mesh grows by a factor of 1024,
    with the wall time flat at 15-18 s throughout."""
    h = spinless_chain()
    V = density_interaction(h, V1=0.8)
    ndiag = []
    for nk in (4096, 65536):
        b = h.get_bse(V=V, nk=nk, tda=True, solver="qtt", neig=1,
                      tolerance=1e-8, coarse_nk=8)
        ndiag.append(b.pairs.ndiag())
    assert ndiag[1] < 4 * ndiag[0], ndiag        # far from 16x
    assert ndiag[1] < 65536 / 8, ndiag           # and far below the mesh


def test_qtt_binding_energy_needs_no_mesh_scan():
    """The lowest independent-particle transition, which the binding
    energy is measured from, is the ground state of the diagonal MPO --
    not a minimum over a mesh nobody ever built"""
    h = spinless_chain()
    V = density_interaction(h, V1=0.8)
    nk = 32
    ref = h.get_bse(V=V, nk=nk, tda=True)
    got = h.get_bse(V=V, nk=nk, tda=True, solver="qtt", neig=1,
                    tolerance=1e-10, coarse_nk=8)
    assert abs(got.get_lowest_transition()
               - np.min(ref.pairs.dE)) < 1e-8
    assert abs(got.get_binding_energies()[0]
               - ref.get_binding_energies(n=1)[0].real) < 1e-7
    assert got.get_binding_energies()[0] > 0.  # actually bound


def test_qtt_matches_dense_2d():
    h = gapped_honeycomb(spinful=False)
    V = density_interaction(h, V1=0.6, V2=0.2)
    nk = 8
    ref = h.get_bse(V=V, nk=nk, tda=True).get_energies(n=1)[0].real
    got = h.get_bse(V=V, nk=nk, tda=True, solver="qtt", neig=1,
                    tolerance=1e-10, coarse_nk=4,
                    maxdim=200).get_energies()[0].real
    assert abs(got - ref) < 1e-6, (got, ref)


def test_qtt_spinful_matches_dense():
    """Degenerate multiplets throughout, so the projection gauge is doing
    the work here -- the phase gauge cannot smooth this model at all"""
    h = gapped_ionic_chain()
    V = density_interaction(h, U=1.0, V1=0.5)
    nk = 8
    ref = h.get_bse(V=V, nk=nk, tda=True).get_energies(n=1)[0].real
    got = h.get_bse(V=V, nk=nk, tda=True, solver="qtt", neig=1,
                    tolerance=1e-10, coarse_nk=8).get_energies()[0].real
    assert abs(got - ref) < 1e-7, (got, ref)


def test_excited_excitons_are_refused():
    """The overlap-penalty DMRG does not converge on this problem -- it
    returned energies up to 0.4 off, and sometimes below the true
    eigenvalue, at every penalty weight tried -- so neig>1 is refused
    rather than approximated. See solve_qtt's message for the numbers."""
    h = spinless_chain()
    V = density_interaction(h, V1=0.8)
    with pytest.raises(ValueError, match="lowest exciton only"):
        h.get_bse(V=V, nk=8, tda=True, solver="qtt", neig=3)


@pytest.mark.parametrize("unfolding", ["grouped", "interleaved"])
def test_both_bit_orderings_give_the_same_answer(unfolding):
    """The bit ordering is a representation choice, so it changes the
    ranks (grouped measured lower on every 2D case) and must not change
    the answer"""
    h = gapped_honeycomb(spinful=False)
    V = density_interaction(h, V1=0.6, V2=0.2)
    nk = 8
    ref = h.get_bse(V=V, nk=nk, tda=True).get_energies(n=1)[0].real
    got = h.get_bse(V=V, nk=nk, tda=True, solver="qtt", neig=1,
                    tolerance=1e-10, coarse_nk=4, maxdim=200,
                    unfolding=unfolding).get_energies()[0].real
    assert abs(got - ref) < 1e-6, (unfolding, got, ref)


def test_qtt_amplitudes_are_the_eigenvector():
    """The returned amplitudes must actually solve the problem, not just
    have the right shape"""
    h = spinless_chain()
    W = bare_interaction(h, V=density_interaction(h, V1=0.8))
    V = density_interaction(h, V1=0.8)
    nk = 16
    # coarse_nk=nk so the oracle picks its gauge references off the same
    # mesh PairBasis does: the amplitudes of two different gauges differ
    # by a diagonal unitary and are eigenvectors of two different (though
    # isospectral) matrices, so comparing them across gauges is meaningless
    b = h.get_bse(V=V, nk=nk, tda=True, solver="qtt", neig=1,
                  tolerance=1e-12, coarse_nk=nk)
    pb = PairBasis(h, nk=nk, gauge="projection")
    f = KernelFactorization(pb, W, Wx=W, kernel="full", block="A")
    x = b.amplitudes[0]
    x = x / np.linalg.norm(x)
    e = b.get_energies()[0].real
    assert np.linalg.norm(f.matvec(x) - e * x) < 1e-6


# ------------------------------------------------------------- the edges

def test_non_power_of_two_mesh_is_refused():
    h = spinless_chain()
    V = density_interaction(h, V1=0.8)
    with pytest.raises(ValueError, match="power of two"):
        h.get_bse(V=V, nk=12, tda=True, solver="qtt")


def test_tabulated_screening_is_refused():
    h = spinless_chain()
    V = density_interaction(h, V1=0.8)
    with pytest.raises(ValueError, match="real-space interaction"):
        h.get_bse(V=V, nk=8, tda=True, solver="qtt", screening="rpa")


def test_full_problem_is_refused():
    h = spinless_chain()
    V = density_interaction(h, V1=0.8)
    with pytest.raises(ValueError, match="Tamm-Dancoff"):
        h.get_bse(V=V, nk=8, tda=False, solver="qtt")
