import numpy as np
from ..multihopping import MultiHopping


def bare_interaction(h,V=None):
    """Return the bare two-body density-density interaction of h, as a
    real-space dictionary {(n1,n2,n3): W} with the unambiguous convention

        H_int = (1/2) sum_{R,R'} sum_{ij} W_ij(R'-R) n_{Ri} n_{R'j}

    where i,j run over the spin-orbitals of the unit cell and n_{Ri} is the
    number operator of orbital i in cell R. Both orderings (i,j) and (j,i)
    are present in the sum, which is what the leading 1/2 compensates.

    IMPORTANT -- the factor of two. The interaction the SCF stores on a
    converged Hamiltonian as h.V (scftk/densitydensity.py's `v`)
    is NOT W: it is W/2. That is a mean-field-decoupling convention, not a
    different physical interaction, and it is easy to miss:
    Vinteraction builds its neighbor shells with `[V1/2.,V2/2.,V3/2.]` and
    adds the Hubbard term as `v[(0,0,0)][2i,2i+1] += U/2`, and
    get_mf_normal then picks up each unordered pair twice (once from
    direction d and once from -d, and once from the term itself and once
    from its dagger), so the mean field it produces is the one generated by
    W = 2*v, not by v. Concretely, for a Hubbard U the stored v has
    v[(0,0,0)][up,dn] = v[(0,0,0)][dn,up] = U/2, and W = 2*v gives
    W[up,dn] = W[dn,up] = U, which put into the formula above returns
    exactly U*n_up*n_dn. tests/bse/test_bse_interaction.py checks this
    against the SCF's own get_mf_normal rather than trusting the algebra.

    V lets the caller override the interaction instead of reading h.V:
      - None (default): use h.V, i.e. the interaction of the mean field h
        was converged with. This is the self-consistent choice -- the same
        W generates the Fock self-energy already inside h and the direct
        BSE kernel, so there is no double counting (BSE-on-top-of-HF is
        then exactly time-dependent Hartree-Fock).

        The factor of two above applies to every channel that stores an
        h.V, not only the density-density ones: the spin-exchange channels
        (SzSz/Jinteraction/VJinteraction's J1/J2/J3, built by
        scftk.spinspin._build_v) write Sz_i Sz_j out as the
        +-1/4 sign pattern of (n_iu-n_id)(n_ju-n_jd) in the spin-orbital
        blocks and are then decoupled by the very same get_mf_normal, so
        they are density-density matrices in the spin-orbital basis too
        and are read correctly here.

        What h.V does NOT capture is worth knowing before relying on this
        default (spinspin.py says the same about its own consumers):
          - after an *anisotropic* exchange run (J1x/J1y alongside J1z),
            h.V holds the z channel only, never the x/y ones -- there is
            no single matrix that represents that interaction, so the
            kernel built from it is incomplete rather than merely scaled
          - after SxSx/SySy, h.V is expressed in the internally-rotated
            frame the SCF ran in, while the returned Hamiltonian is
            rotated back, so the two do not share a spin frame
        In both cases pass W explicitly instead of relying on h.V.
      - a dict / MultiHopping {(n1,n2,n3): matrix}: used directly as W (NOT
        halved -- a user-supplied interaction is taken at face value, in
        the H_int convention above).
      - a plain matrix: treated as an onsite-only W, i.e. {(0,0,0): matrix}.
    """
    if hasattr(V,"at"): return V # already a tabulated interaction
    if V is None: # read the interaction off the mean-field Hamiltonian
        if getattr(h,"V",None) is None:
            raise ValueError("this Hamiltonian carries no interaction "
                "(h.V is not set), so there is no BSE kernel to build. "
                "Either pass V explicitly, or start from a Hamiltonian "
                "returned by a mean-field calculation "
                "(get_mean_field_hamiltonian), which stores the "
                "interaction it converged with as h.V")
        v = V2dict(h.V)
        return {d: 2.*np.array(m,dtype=np.complex128) for d,m in v.items()}
    else: # explicit interaction, taken at face value
        v = V2dict(V)
        return {d: np.array(m,dtype=np.complex128) for d,m in v.items()}


def V2dict(V):
    """Normalize an interaction to a {direction: matrix} dictionary"""
    if isinstance(V,MultiHopping): return V.get_dict()
    if isinstance(V,dict): return V
    return {(0,0,0): np.array(V,dtype=np.complex128)} # onsite-only matrix


def qkey(q):
    """Hashable key identifying a q-point modulo a reciprocal lattice
    vector. Used both to collapse the k-k' differences of a mesh onto the
    nk distinct ones (kernel.qdifference_map) and to look a q-point up in
    a tabulated screened interaction (screening.ScreenedInteraction),
    which only agree if both use the same key. The second %1.0 is not
    redundant: it catches a value that rounds up to 1.0."""
    q = np.mod(np.array(q,dtype=np.float64),1.0) # fold into [0,1)
    return tuple(np.round(q,7)%1.0)


def interaction_at_q(W,g,q):
    """Fourier transform a real-space interaction dictionary at a q-point,
    W(q) = sum_d W(d) exp(2 pi i q.d). This is the exact same Bloch-phase
    convention (geometry.bloch_phase) that htk.bloch uses to build H(k)
    from a hopping dictionary, which is why the tight-binding coefficients
    C^{nk} and the interaction W(q) share a gauge in the BSE kernel with no
    extra intracell-position phases: pyqula works in the cell gauge, where
    the Bloch phase depends only on the lattice vector and not on the
    positions inside the unit cell.

    W may also be a tabulated screening.ScreenedInteraction rather than a
    real-space dictionary, in which case there is nothing to transform and
    the value stored at that q is returned -- see its .at method for what
    happens when q is not a mesh point."""
    if hasattr(W,"at"): return W.at(q) # tabulated on a mesh, not a dict
    out = None
    for d,m in W.items():
        phase = g.bloch_phase(d,q)
        out = m*phase if out is None else out + m*phase
    return out


def density_interaction(h,U=0.,V1=0.,V2=0.,V3=0.,Vr=None):
    """Build a density-density interaction W in this module's convention
    (see bare_interaction) from neighbor-shell couplings, using the same
    U/V1/V2/V3/Vr meaning scftk.densitydensity.Vinteraction and
    Hamiltonian.get_mean_field_hamiltonian use:

      H_int = U sum_i n_i,up n_i,dn + sum_shells V_s sum_<ij>_s n_i n_j

    with n_i the total density of site i. Unlike Vinteraction this returns
    the bare W (not W/2), so it can be handed straight to the BSE as V=.

    This is the constructor to use for a screened interaction that is not
    the one the mean field was converged with -- a Hubbard-only h.V is far
    too short-ranged to bind a Wannier-Mott exciton, so realistic exciton
    calculations want a long-ranged Vr here (e.g. a Rytova-Keldysh or
    cut-off Coulomb tail) even when the mean field itself came from a
    plain Hubbard SCF.

    Vr, if given, is a function of TWO position vectors, Vr(r1,r2),
    exactly as Vinteraction's own Vr: it is passed to
    Geometry.get_hamiltonian as tij, which calls it once per pair of sites.
    A Coulomb tail is therefore written Vr=lambda r1,r2: e2/abs(r1-r2),
    and must stay finite at r1==r2 -- get_hamiltonian evaluates the
    diagonal too. The same-site diagonal it produces is discarded below
    (an electron does not interact with itself), so a soft cutoff there is
    only needed to avoid a division by zero, not to get the physics right.
    """
    from .. import specialhopping
    nd = h.geometry.neighbor_distances() # neighbor shell distances
    mgenerator = specialhopping.distance_hopping_matrix([V1,V2,V3],nd[0:3])
    hv = h.geometry.get_hamiltonian(has_spin=False,is_multicell=True,
            mgenerator=mgenerator)
    if Vr is not None:
        hv = hv + h.geometry.get_hamiltonian(has_spin=False,
                is_multicell=True,tij=Vr)
    v = hv.get_hopping_dict() # spinless, site-resolved
    # drop the same-site self-interaction: get_hamiltonian(tij=Vr)
    # evaluates the interaction for every pair of sites including a site
    # with itself, and an electron does not interact with itself. The
    # neighbor-shell part never produces one (zero distance is not a
    # shell), but a Vr tail always does.
    np.fill_diagonal(v[(0,0,0)],0.)
    if not h.has_spin: # spinless, nothing else to do
        if U!=0.:
            raise ValueError("a Hubbard U has no meaning for a spinless "
                "Hamiltonian (there is no second spin species to repel)")
        return {d: np.array(m,dtype=np.complex128) for d,m in v.items()}
    # spinful: every spin-orbital of site i couples to every one of site j
    from ..scftk.densitydensity import obj2geometryarray
    Ua = obj2geometryarray(U,h.geometry)
    out = dict()
    for d,m in v.items():
        ns = m.shape[0]
        m1 = np.zeros((2*ns,2*ns),dtype=np.complex128)
        for i in range(ns):
            for j in range(ns):
                m1[2*i:2*i+2,2*j:2*j+2] = m[i,j]
        out[d] = m1
    ns = len(h.geometry.r)
    for i in range(ns): # onsite Hubbard, up-down only
        out[(0,0,0)][2*i,2*i+1] += Ua[i]
        out[(0,0,0)][2*i+1,2*i] += Ua[i]
    return out
